import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import RepoList from '@/components/repolist';
import { GetServerSideProps } from 'next';

import {getRepoData} from '@/lib/repos';
const inter = Inter({ subsets: [ 'latin' ] });
export const getServerSideProps: GetServerSideProps = async () => {
  const repos = await getRepoData();
  return {
    props:{
      repos:repos
    }
  };
};

export default function Home({repos}:{repos:any}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className=''>
          <RepoList repos={repos} />
        </div>
      </main>
    </>
  );
}
